# Generated by Django 4.2.29 on 2026-03-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalytics',
            name='discount_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockanalytics',
            name='one_year_high',
            field=models.FloatField(default=0.0),
        ),
    ]
