name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "."
          target: ${{ secrets.SERVER_PATH }}
          rm: false

      - name: Execute remote commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ secrets.SERVER_PATH }}/frontend
            echo "VITE_API_BASE_URL=https://euitylens.duckdns.org/api/" > .env
            echo "VITE_MEDIA_URL=https://euitylens.duckdns.org" >> .env
            npm install
            npm run build
            
            cd ${{ secrets.SERVER_PATH }}/backend
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            
            pm2 restart equitylens
            sudo systemctl restart nginx
            echo "Deployment finished successfully!"
