# Generated by Django 6.0.2 on 2026-03-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='current_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
